/* Skill Development — documented programmes and general skill areas. Do not label every item as an ITDA programme. */

(function loadSkillDevelopment() {
  const NA = typeof window.NA === "string" ? window.NA : "Information not available in the supplied source.";
  const VERIFY = "Verify latest official records.";

  educationData.skillDevelopment = {
    overview: "Skill development in the ITDA Paderu / ASR District context includes academic-to-career coaching, employment support, coffee livelihood training, tribal livelihood action research and technology fellowships. Each activity is shown with its actual implementing organisation. This module does not call every activity an “ITDA Skill Development Programme.”",
    namingNote: "Keep Administrative Authority, Project Officer, Conducted By and Training Partner as four separate fields. The Project Officer does not personally conduct every training activity.",
    about: {
      intro: "Skill development at ITDA Paderu focuses on creating opportunities for students, tribal youth and communities to develop practical, employment-oriented and livelihood-based skills.",
      whoMayBeInvolved: "Depending on the activity, work may involve ITDA Paderu, district departments, government agencies, training organisations, technical institutions and industry partners.",
      focusAreas: [
        "Digital and computer skills",
        "Technology and software development",
        "Artificial Intelligence",
        "Employment and career guidance",
        "Vocational skills",
        "Agriculture and horticulture",
        "Coffee-related livelihood development",
        "Tribal handicrafts and traditional skills",
        "Tourism and hospitality",
        "Entrepreneurship",
        "Job and placement support"
      ]
    },
    administration: {
      administrativeAuthority: "Integrated Tribal Development Agency (ITDA), Paderu",
      projectOfficer: "Sri Aditya Verma, IAS",
      projectOfficerDesignation: "Project Officer, ITDA, Paderu",
      projectOfficerYear: "2026",
      projectOfficerSource: "ASR District All India Services page currently lists Sri Aditya Verma, IAS in this position (as supplied).",
      skillOffice: "ITDA Office, Paderu",
      skillOfficerDesignation: "District Skill Development Officer",
      skillOfficerName: NA,
      skillOfficerSource: "The district Who’s Who page lists the District Skill Development Officer under Skill Development at ITDA Office, Paderu. The officer’s personal name is not published here."
    },
    implementingDistinction: [
      { activity: "Sisal / Lantana fibre project", presentation: "Paderu ITDA Agency Area + Ministry of Tribal Affairs supported project" },
      { activity: "Coffee training", presentation: "Coffee Board, Paderu + relevant local agencies" },
      { activity: "Job Melas", presentation: "District Employment Exchange" },
      { activity: "Career Guidance", presentation: "District Employment Exchange / Education system" },
      { activity: "Super 50", presentation: "Tribal Welfare / ITDA Paderu" },
      { activity: "AAROHAN", presentation: "ITDA Paderu in association with Datapro Computers Pvt. Ltd. (as printed on the 2026 programme posters)" },
      { activity: "Coffee Experience Centre", presentation: "ITDA Paderu project" }
    ],
    programmes: [
      {
        id: "aarohan",
        documented: true,
        kind: "programme",
        name: "AAROHAN AI Fellowship Programme 2026",
        year: "2026",
        duration: NA,
        category: "Technology & AI",
        administrativeAuthority: "ITDA Paderu",
        projectOfficer: "Sri Aditya Verma, IAS",
        projectOfficerDesignation: "Project Officer, ITDA, Paderu",
        conductedBy: "Datapro Computers Pvt. Ltd.",
        partner: "Datapro Computers Pvt. Ltd.",
        focus: "Empowering tribal youth through AI, technology and innovation (AI, data, full stack), as printed on the 2026 fellowship poster",
        target: "Selected students / tribal youth",
        type: "AI Fellowship Programme",
        trainingType: "Classroom + practical + project / challenge-based (as shown in programme materials)",
        assessment: NA,
        careerFocus: "Technology skills and tribal youth leadership (poster wording: Learn. Build. Lead. Inspire.)",
        status: "Current / 2026",
        locations: ["Government Tribal Welfare Post Metric Hostel (Girls), Kakarapadu (V), Koyyuru Mandal — PIN 531 087 (as printed on the 2026 posters)"],
        activities: ["Technical training", "Mentorship", "Real-world / real-time web projects", "API and Ollama AI practice (WebPulse challenge)", "Computer-lab coding practice"],
        learn: ["AI", "Data", "Full stack", "HTML5", "CSS3", "JavaScript", "Third-party APIs", "Ollama API"],
        objective: "The 2026 posters describe AAROHAN as an AI Fellowship Programme to empower tribal youth through AI, technology and innovation.",
        journey: ["Selection", "Orientation / inauguration", "Technical training", "Practical lab work", "Challenge / project (WebPulse)", "Career-oriented learning"],
        events: [
          {
            name: "AAROHAN WebPulse 2026 — Real-Time Web Integration Challenge",
            date: "26 September 2026 (Saturday)",
            time: "9:30 AM to 6:30 PM",
            items: [
              "Theme printed on the poster: Connect · Fetch · Innovate",
              "Technologies: HTML5, CSS3, JavaScript, third-party APIs, Ollama API",
              "Team size: 5 members per team",
              "Total teams: 10",
              "Venue printed on the poster: Government Tribal Welfare Post Metric Hostel (Girls), Kakarapadu (V), Koyyuru Mandal — 531 087",
              "In association with: ITDA Paderu | Datapro Computers Pvt. Ltd."
            ]
          }
        ],
        overview: "AAROHAN AI Fellowship Programme 2026 is shown on ITDA Paderu programme posters as a technology fellowship for tribal youth, in association with Datapro Computers Pvt. Ltd. The printed venue is the Government Tribal Welfare Post Metric Hostel (Girls), Kakarapadu village, Koyyuru mandal (PIN 531 087). A related 2026 activity on the same posters is AAROHAN WebPulse, a real-time web integration challenge.",
        source: "Programme posters and photographs supplied for this website: AAROHAN AI Fellowship Programme 2026 and AAROHAN WebPulse 2026, printed in association with ITDA Paderu and Datapro Computers Pvt. Ltd.",
        caution: "Officer and guest names in the inauguration photograph are not published here. Batch size, fees and a full module list beyond what is printed on the posters are not invented. Python / Machine Learning / Deep Learning are not listed as confirmed AAROHAN modules on these posters.",
        photos: "Supplied programme photographs and posters",
        documents: NA
      },
      {
        id: "employment",
        documented: true,
        kind: "programme",
        name: "Employment & Job Mela Activities",
        year: "Continuing (district employment system)",
        duration: NA,
        category: "Employment-oriented skill / job support",
        administrativeAuthority: "District Employment Exchange, Alluri Sitharama Raju District",
        projectOfficer: NA,
        projectOfficerDesignation: NA,
        conductedBy: "District Employment Exchange",
        partner: NA,
        focus: "Registration, career guidance, job matching and Job Melas for unemployed youth, with special focus on ST youth",
        target: "Unemployed youth (special focus: ST youth)",
        type: "Employment support",
        trainingType: NA,
        assessment: NA,
        careerFocus: "Candidate → Employer → Employment",
        status: "Documented district activity",
        activities: ["Career guidance", "Employability awareness", "Job-matching support", "Job Melas", "Public-sector employment awareness", "Private-sector employment opportunities", "Youth registration", "Candidate sponsorship"],
        learn: [],
        objective: "To connect eligible job seekers with employment opportunities and provide career guidance.",
        journey: ["Youth registration", "Record update", "Career guidance", "Job Mela / vacancy sponsorship", "Employer matching", "Employment"],
        locations: ["Araku", "Paderu", "Chintapalli"],
        overview: "The District Employment Exchange, ASR District, provides employment-related support to unemployed ST youth. Official district information states that the Exchange registers unemployed ST youth, updates employment records, sponsors eligible candidates against notified vacancies, conducts Job Melas and provides career guidance. Job Melas are conducted at Araku, Paderu and Chintapalli according to the district’s published information.",
        source: "District Employment Exchange published information (as supplied).",
        caution: "This is not presented as an ITDA-run Job Mela programme. Current vacancy lists are not published here.",
        photos: NA,
        documents: NA
      },
      {
        id: "career",
        documented: true,
        kind: "programme",
        name: "Career Guidance Programmes",
        year: "Continuing",
        duration: NA,
        category: "Career guidance",
        administrativeAuthority: "District Employment Exchange / Education system",
        projectOfficer: NA,
        projectOfficerDesignation: NA,
        conductedBy: "District Employment Exchange (career-guidance classes in government schools, municipal schools and government colleges, as officially reported)",
        partner: NA,
        focus: "Education and employment pathway awareness",
        target: "Students and youth",
        type: "Career guidance",
        trainingType: NA,
        assessment: NA,
        careerFocus: "Education → Career awareness → Career selection → Skill development → Qualification → Job / Higher education / Entrepreneurship",
        status: "Documented district activity",
        activities: ["Career awareness", "Government employment opportunities", "Private-sector opportunities", "Higher education", "Competitive examinations", "Skill development", "Resume preparation", "Interview awareness", "Employment registration"],
        learn: [],
        objective: "Help students understand different education and employment pathways.",
        journey: ["Education", "Career Awareness", "Career Selection", "Skill Development", "Qualification", "Job / Higher Education / Entrepreneurship"],
        overview: "Career guidance activities help students understand education and employment pathways. The District Employment Exchange officially reports conducting career-guidance classes in government schools, municipal schools and government colleges.",
        source: "District Employment Exchange official reporting (as supplied).",
        caution: "Presented as District Employment Exchange / Education system activity, not as a generic ITDA Skill Development Programme.",
        photos: NA,
        documents: NA
      },
      {
        id: "coffee",
        documented: true,
        kind: "programme",
        name: "Coffee Skill & Livelihood Development",
        year: "Continuing (Coffee Board extension; including 2023–24 and 2024–25 livelihood skills)",
        duration: NA,
        category: "Livelihood / coffee",
        administrativeAuthority: "Coffee Board of India, Paderu Extension Office (technical agency)",
        projectOfficer: NA,
        projectOfficerDesignation: NA,
        conductedBy: "Coffee Board of India, Paderu",
        partner: "Nodal agencies including ITDA and GCC for coffee area expansion and marketing support (as described by the Coffee Board)",
        focus: "Sustainable coffee cultivation and grower capacity",
        target: "Coffee growers / tribal communities",
        type: "Livelihood skill / extension",
        trainingType: "Workshops, demonstrations, exposure visits",
        assessment: NA,
        careerFocus: "Improved coffee production and market opportunities",
        status: "Continuing Coffee Board extension activities",
        activities: ["Village-level workshops", "Capacity-building programmes", "Exposure visits", "Field demonstrations", "Technology transfer", "Sustainable coffee cultivation", "Coffee area expansion", "Technical support", "Quality improvement", "Marketing support", "Scientific cultivation"],
        learn: [],
        objective: "Improve the socioeconomic status of tribal communities and support sustainable coffee cultivation (Coffee Board stated objective, as supplied).",
        journey: ["Coffee Cultivation", "Field Training", "Harvesting", "Processing", "Quality Improvement", "Marketing", "Value Addition", "Livelihood / Entrepreneurship"],
        overview: "Coffee-related skill development is an important livelihood area in the Paderu / Araku agency area. The Coffee Board of India, Paderu Extension Office, describes continuing village workshops, capacity building, exposure visits, field demonstrations, technology transfer and sustainable coffee cultivation training. The Board also works with nodal agencies including ITDA and GCC for coffee area expansion and marketing support.",
        source: "Coffee Board of India, Paderu Extension Office descriptions (as supplied).",
        caution: "Presented as Coffee Board training with local agency coordination — not as an ITDA-only skill programme.",
        photos: NA,
        documents: NA
      },
      {
        id: "coffee-experience",
        documented: true,
        kind: "project",
        name: "Coffee Experience Centre",
        year: NA,
        duration: NA,
        category: "Livelihood / coffee",
        administrativeAuthority: "ITDA Paderu",
        projectOfficer: NA,
        projectOfficerDesignation: NA,
        conductedBy: "ITDA Paderu project",
        partner: NA,
        focus: NA,
        target: NA,
        type: "ITDA Paderu project",
        trainingType: NA,
        assessment: NA,
        careerFocus: NA,
        status: "Named as an ITDA Paderu project in the supplied brief",
        activities: [],
        learn: [],
        objective: NA,
        journey: [],
        overview: "The Coffee Experience Centre is presented as an ITDA Paderu project. Course lists, dates, visitor numbers and building details are not in the supplied source.",
        source: "ITDA Paderu project naming in the supplied Skill Development brief.",
        caution: "Do not invent visitor programmes, fees or a training calendar.",
        photos: NA,
        documents: NA
      },
      {
        id: "sisal",
        documented: true,
        kind: "programme",
        name: "Sisal & Lantana Fibre Skill Development",
        year: "2022–23 (Action Research record)",
        duration: NA,
        category: "Tribal livelihood / alternative livelihood",
        administrativeAuthority: "Paderu ITDA Agency Area (location of the initiative)",
        projectOfficer: NA,
        projectOfficerDesignation: NA,
        conductedBy: "Ministry of Tribal Affairs supported Action Research",
        partner: NA,
        focus: "Extraction of fibre from Sisal leaves and Lantana plants",
        target: "17 tribal groups",
        type: "Action Research / livelihood development",
        trainingType: NA,
        assessment: NA,
        careerFocus: "Alternative livelihood opportunities",
        status: "Documented MoTA Action Research",
        activities: ["Fibre extraction skill development", "Value addition from Sisal leaves and Lantana"],
        learn: [],
        objective: "Create alternative livelihoods for 17 tribal groups in the Paderu ITDA Agency Area.",
        journey: ["Local Natural Resources", "Fibre Extraction", "Skill Development", "Product Development", "Value Addition", "Market Opportunity", "Alternative Livelihood"],
        location: "Paderu ITDA Agency Area",
        overview: "The Ministry of Tribal Affairs approved an Action Research on Skill Development on extraction of fibre from Sisal leaves and Lantana plants to create alternative livelihoods for 17 tribal groups in the Paderu ITDA Agency Area.",
        source: "Ministry of Tribal Affairs sanction / Action Research record (as supplied).",
        caution: "Presented as a MoTA-supported project in the Paderu ITDA Agency Area — not as a generic ITDA Skill Development Programme.",
        photos: NA,
        documents: NA
      },
      {
        id: "super50-pathway",
        documented: true,
        kind: "programme",
        name: "Super 50 — Academic-to-Career Skill Development",
        year: "2023–24; 2024–25; 2025–26",
        duration: NA,
        category: "Academic coaching / career pathway",
        administrativeAuthority: "Tribal Welfare / ITDA Paderu",
        projectOfficer: NA,
        projectOfficerDesignation: NA,
        conductedBy: "Tribal Welfare Department (as documented)",
        partner: NA,
        focus: "Focused coaching and mentoring for high-performing tribal SSC students",
        target: "High-performing tribal SSC students",
        type: "Academic-to-career pathway (Tribal Welfare Super 50)",
        trainingType: "Special coaching",
        assessment: NA,
        careerFocus: "SSC academic performance and further study pathways",
        status: "Documented Tribal Welfare programme",
        activities: ["Screening", "Merit selection", "Coaching centres", "Special coaching"],
        learn: [],
        objective: "Provide focused academic coaching and mentoring to selected SSC students (Tribal Welfare Super 50).",
        journey: ["Screening", "Selection", "Coaching centre", "SSC preparation", "Further study pathway"],
        overview: "Although Super 50 is primarily an academic coaching programme, it is listed here as an education-to-skill/career pathway. Year-wise figures are those reported by the Tribal Welfare Department.",
        source: "Official Tribal Welfare Super 50 reporting (as supplied).",
        caution: "Full year-wise Super 50 figures remain on Student Programmes → Super 50. This card does not invent additional batches.",
        yearWise: [
          {
            year: "2025–26",
            items: [
              "Screening conducted on 1 September 2025",
              "104 merit students selected",
              "51 boys",
              "53 girls",
              "Coaching centres opened at Paderu and Chintapalli",
              "Coaching started from 7 October 2025"
            ]
          }
        ],
        relatedHref: "#studentProgrammes/cat/super50/prog/super50",
        photos: NA,
        documents: NA
      },
      {
        id: "vocational",
        documented: false,
        kind: "area",
        name: "Vocational Skills — Tailoring & Electrical",
        year: NA,
        duration: NA,
        category: "Vocational skills (general)",
        administrativeAuthority: NA,
        projectOfficer: NA,
        projectOfficerDesignation: NA,
        conductedBy: NA,
        partner: NA,
        focus: "Tailoring, sewing, electrical and workshop practice",
        target: "Youth (general)",
        type: "Skill area — not a named ITDA batch unless official records confirm it",
        trainingType: NA,
        assessment: NA,
        careerFocus: "Tailoring, electrical work, workshop trades (career labels, not vacancy lists)",
        status: "General skill area",
        activities: ["Tailoring", "Sewing", "Electrical wiring", "Workshop practice", "Motor / appliance basics"],
        learn: [],
        objective: "Vocational skills can support employability and self-employment. Individual centre names are shown only when they appear on a photograph or official record.",
        journey: ["Skill practice", "Trade learning", "Employability / self-employment"],
        overview: "Vocational tailoring and electrical workshop photographs are listed here as skill areas. A sewing-school banner visible in one photograph is not treated as an ITDA Paderu programme unless official records confirm it.",
        source: "Photographs supplied for vocational skill topics.",
        caution: "General skill/career information. Not presented as a specific ITDA programme unless an official source confirms it.",
        photos: NA,
        documents: NA
      },
      {
        id: "handicrafts",
        documented: false,
        kind: "area",
        name: "Tribal Handicraft & Traditional Skills",
        year: NA,
        duration: NA,
        category: "Traditional skills / proposed tourism linkage",
        administrativeAuthority: NA,
        projectOfficer: NA,
        projectOfficerDesignation: NA,
        conductedBy: NA,
        partner: NA,
        focus: "Traditional tribal skills and local products (general skill areas)",
        target: NA,
        type: "Skill area (not a completed named training calendar)",
        trainingType: NA,
        assessment: NA,
        careerFocus: NA,
        status: "Skill areas + proposed Art Village (district tourism page)",
        activities: ["Bamboo craft", "Cane work", "Pottery", "Clay modelling", "Tribal jewellery", "Traditional art", "Handicraft product development", "Product finishing", "Packaging", "Branding", "Marketing"],
        learn: [],
        objective: NA,
        journey: [],
        overview: "Skill-development and livelihood initiatives can also focus on traditional tribal skills and local products. The district tourism page describes a proposed Art Village around pottery, bamboo/cane handicrafts, metal craft and tribal jewellery. That Art Village is labelled here as a proposed initiative, not as a completed training programme.",
        source: "District tourism page (proposed Art Village) plus general traditional-skill areas in the supplied brief.",
        caution: "Do not present the Art Village as a running ITDA training programme.",
        photos: NA,
        documents: NA
      },
      {
        id: "digital",
        documented: false,
        kind: "area",
        name: "Digital & Technology Skill Development",
        year: NA,
        duration: NA,
        category: "Digital skills (general)",
        administrativeAuthority: NA,
        projectOfficer: NA,
        projectOfficerDesignation: NA,
        conductedBy: NA,
        partner: NA,
        focus: "Modern technology capabilities for students and youth",
        target: "Students and youth (general)",
        type: "Skill area — not a named ITDA batch unless official records confirm it",
        trainingType: NA,
        assessment: NA,
        careerFocus: "Web Developer, Software Developer, Python Developer, Full-Stack Developer, Data Analyst, AI/ML Trainee, IT Support (career labels, not vacancy lists)",
        status: "General skill area",
        activities: ["Computer fundamentals", "Internet usage", "Digital services", "Web development", "Programming", "Database management", "Mobile applications", "Cloud technologies", "Artificial Intelligence", "Data Analytics"],
        learn: [],
        objective: "Digital skill programmes can help students and youth develop modern technology capabilities.",
        journey: [],
        overview: "Digital skill areas listed for awareness. They are not presented as official ITDA courses unless a specific programme record confirms them. AAROHAN (2026) is the documented technology fellowship in this module.",
        source: "General skill/career information in the supplied brief.",
        caution: "General skill/career information. Not presented as a specific ITDA programme unless an official source confirms it.",
        photos: NA,
        documents: NA
      },
      {
        id: "ai",
        documented: false,
        kind: "area",
        name: "AI & Emerging Technology",
        year: NA,
        duration: NA,
        category: "Emerging technology (general)",
        administrativeAuthority: NA,
        projectOfficer: NA,
        projectOfficerDesignation: NA,
        conductedBy: NA,
        partner: NA,
        focus: "Introduction to emerging technologies",
        target: "Students and youth (general)",
        type: "Skill area",
        trainingType: NA,
        assessment: NA,
        careerFocus: NA,
        status: "General skill area; AAROHAN is the documented 2026 AI fellowship",
        activities: ["Artificial Intelligence", "Machine Learning", "Deep Learning", "Generative AI", "Large Language Models", "AI Chatbots", "Prompt Engineering", "Computer Vision", "Data Analytics", "AI-powered applications"],
        learn: [],
        objective: "Technology-focused programmes can introduce students to emerging technologies.",
        journey: ["ITDA Website", "Student-developed Chatbot", "AI / Ollama", "Government Information", "Student / Citizen Question", "Answer"],
        overview: "Emerging-technology topics are listed as learning areas. Machine Learning and Deep Learning are not published here as confirmed AAROHAN syllabus items. An example project concept is an ITDA AI Information Assistant using verified ITDA information and a stated source.",
        source: "General emerging-technology areas in the supplied brief. Example project is a concept, not a notified scheme.",
        caution: "This is a general skill area. Named 2026 AAROHAN modules are only those printed on the AAROHAN posters (AI, data, full stack, web APIs / Ollama API). Python, Machine Learning and Deep Learning are not published as confirmed AAROHAN syllabus items.",
        photos: NA,
        documents: NA
      },
      {
        id: "agriculture",
        documented: false,
        kind: "area",
        name: "Agriculture & Horticulture Skills",
        year: NA,
        duration: NA,
        category: "Agriculture / horticulture (general)",
        administrativeAuthority: NA,
        projectOfficer: NA,
        projectOfficerDesignation: NA,
        conductedBy: NA,
        partner: NA,
        focus: "Agriculture and horticulture livelihoods",
        target: NA,
        type: "Skill area",
        trainingType: NA,
        assessment: NA,
        careerFocus: "Agriculture Training → Practical Experience → Production → Processing → Packaging → Marketing → Entrepreneurship",
        status: "General skill area",
        activities: ["Modern farming", "Horticulture", "Nursery management", "Organic farming", "Soil management", "Irrigation", "Crop management", "Post-harvest management", "Food processing", "Packaging", "Marketing"],
        learn: [],
        objective: "Skill-development activities can support agriculture and horticulture livelihoods.",
        journey: ["Agriculture Training", "Practical Experience", "Production", "Processing", "Packaging", "Marketing", "Entrepreneurship"],
        overview: "Agriculture and horticulture skill areas. Named ITDA course batches, grant amounts and calendars are not invented here.",
        source: "General skill/career information in the supplied brief.",
        caution: "General skill/career information. Not presented as a specific ITDA programme unless an official source confirms it.",
        photos: NA,
        documents: NA
      },
      {
        id: "tourism",
        documented: false,
        kind: "area",
        name: "Tourism & Hospitality Skills",
        year: NA,
        duration: NA,
        category: "Tourism / hospitality (general)",
        administrativeAuthority: NA,
        projectOfficer: NA,
        projectOfficerDesignation: NA,
        conductedBy: NA,
        partner: NA,
        focus: "Hospitality, guiding, local culture and eco-tourism",
        target: NA,
        type: "Skill area",
        trainingType: NA,
        assessment: NA,
        careerFocus: "Tourism career / entrepreneurship",
        status: "General skill area",
        activities: ["Hospitality", "Tour guiding", "Food services", "Local culture interpretation", "Eco-tourism", "Tourism management", "Digital tourism promotion", "Customer service"],
        learn: ["Communication", "Hospitality", "Local Culture", "Tourism Knowledge", "Digital Skills"],
        objective: "Tourism can create opportunities in hospitality, guiding and related services.",
        journey: [],
        overview: "Tourism and hospitality skill areas. Named ITDA hospitality batches are not published here.",
        source: "General skill/career information in the supplied brief.",
        caution: "General skill/career information. Not presented as a specific ITDA programme unless an official source confirms it.",
        photos: NA,
        documents: NA
      },
      {
        id: "entrepreneurship",
        documented: false,
        kind: "area",
        name: "Entrepreneurship & Self-Employment",
        year: NA,
        duration: NA,
        category: "Enterprise (general)",
        administrativeAuthority: NA,
        projectOfficer: NA,
        projectOfficerDesignation: NA,
        conductedBy: NA,
        partner: NA,
        focus: "Own livelihood opportunities",
        target: "Students and youth (general)",
        type: "Skill area",
        trainingType: NA,
        assessment: NA,
        careerFocus: "Self-employment",
        status: "General skill area",
        activities: ["Agriculture", "Coffee", "Food processing", "Tourism", "Handicrafts", "Bamboo products", "Digital services", "Retail", "Local products"],
        learn: [],
        objective: "Skill development can also help students and youth create their own livelihood opportunities.",
        journey: ["Problem", "Idea", "Market Research", "Business Plan", "Product / Service", "Customer", "Revenue", "Business Growth"],
        overview: "Enterprise pathway information. Scheme finance, loan amounts and current circulars are not listed.",
        source: "General enterprise pathway in the supplied brief.",
        caution: "General skill/career information. Not presented as a specific ITDA programme unless an official source confirms it.",
        photos: NA,
        documents: NA
      }
    ],
    timeline: [
      {
        id: "2021-22",
        year: "2021–22",
        title: "Skill Development Focus",
        text: "Year-specific official records of individual ITDA programmes for 2021–22 are not in the supplied source. This year page lists verified focus areas only. Programme-wise information can be added from ITDA / APSSDC / departmental reports when available.",
        focus: ["Youth employability", "Vocational skills", "Tribal livelihood development", "Agriculture-related skills", "Coffee cultivation knowledge", "Career awareness", "Self-employment"],
        programmes: []
      },
      {
        id: "2022-23",
        year: "2022–23",
        title: "Tribal Livelihood Skill Development — Sisal & Lantana",
        text: "Ministry of Tribal Affairs Action Research on fibre extraction from Sisal leaves and Lantana plants for 17 tribal groups in the Paderu ITDA Agency Area.",
        focus: [],
        programmes: ["sisal"]
      },
      {
        id: "2023-24",
        year: "2023–24",
        title: "Coffee Skill Development & Capacity Building",
        text: "Coffee Board, Paderu, describes village-level workshops, capacity building, exposure visits, field demonstrations, technology transfer, sustainable coffee cultivation, area expansion, technical support, quality improvement and marketing support. Employment, career guidance and job-mela activities can be documented with District Employment Exchange records — they are not relabelled as ITDA programmes.",
        focus: [],
        programmes: ["coffee", "employment", "career"]
      },
      {
        id: "2024-25",
        year: "2024–25",
        title: "Coffee & Livelihood Skills · Employment-Oriented Skill Development",
        text: "Continue Coffee Board village workshops, capacity building, exposure visits, field demonstrations, scientific cultivation, technical support and marketing support. Employment-oriented activities (career guidance, Job Melas at Araku, Paderu and Chintapalli, registration and candidate sponsorship) remain with the District Employment Exchange.",
        focus: [],
        programmes: ["coffee", "employment", "career"]
      },
      {
        id: "2025-26",
        year: "2025–26",
        title: "Super 50 — Academic-to-Career Skill Development",
        text: "Tribal Welfare Super 50 screening on 1 September 2025; 104 merit students (51 boys, 53 girls); coaching centres at Paderu and Chintapalli; coaching from 7 October 2025.",
        focus: [],
        programmes: ["super50-pathway"]
      },
      {
        id: "2026-27",
        year: "2026–27 — Current",
        title: "AAROHAN AI Fellowship Programme 2026",
        text: "AAROHAN AI Fellowship Programme 2026 — ITDA Paderu in association with Datapro Computers Pvt. Ltd. Printed venue: Government Tribal Welfare Post Metric Hostel (Girls), Kakarapadu (V), Koyyuru Mandal — 531 087. Related challenge: AAROHAN WebPulse 2026 (26 September 2026). Project Officer: Sri Aditya Verma, IAS (administrative authority).",
        focus: [],
        programmes: ["aarohan"]
      }
    ],
    categories: [
      { id: "documented", name: "Documented programmes", items: [] },
      { id: "areas", name: "General skill areas", items: [] }
    ]
  };
})();
